modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "createrailwaysnavigator"
version = "${version}"
displayName = "Create Railways Navigator"
authors = "MrJulsen"
updateJSONURL="https://raw.githubusercontent.com/MisterJulsen/Create-Train-Navigator/1.18.2/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator"
issueTrackerURL="https://github.com/MisterJulsen/Create-Train-Navigator/issues"
description = '''
Get possible train connections in your world from one station to another using the Create Railways Navigator. An addon for the Create Mod.
'''
logoFile="icon.png"

[[dependencies.createrailwaysnavigator]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createrailwaysnavigator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createrailwaysnavigator]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createrailwaysnavigator]]
modId = "dragonlib"
mandatory = true
versionRange = "[1.19.2-2.1.8,)"
ordering = "AFTER"
side = "BOTH"